name: Build + Deploy to AKS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------------- Docker build + push ----------------
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: ./stockout-serving
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/stockout-api:latest

      # ---------------- Azure login ----------------
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ---------------- Set AKS context ----------------
      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: stockout-rg
          cluster-name: stockout-aks

      # ---------------- Deploy ----------------
      - name: Deploy to AKS
        run: |
          ls -la
          ls -la stockout-serving
          ls -la stockout-serving/k8s
          kubectl apply -f stockout-serving/k8s/deployment.yaml
          kubectl apply -f stockout-serving/k8s/service.yaml
          kubectl rollout status deployment stockout-api

